# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install python3-pip imagemagick poppler-utils
        run: sudo apt-get install python3-pip imagemagick poppler-utils

      - name: Install uv
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv sync --group test

      - name: Test with pytest
        run: |
          uv run pytest

      # - name: Run mypy
      #   run: |
      #     uv run mypy musurgia --strict
